config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  root "items#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items, path: "photos" do
    resources :selections
    resources :pictures, only: [:create]
  end

  resources :layouts, only: [:index], path: "notre_equipe" 
  resources :carts, only: [:new, :create, :index], path: "mon_panier"
  resources :orders, path: "vos_commandes"
  resources :users, path: "mon_profil"

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :trackable, :timeoutable, :lockable 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :selections
    has_many :items, through: :selections


    def total_cart
        @total_cart = 0

        self.selections.each do |selection|
            @total_cart = selection.item.price + @total_cart
        end
        return @total_cart
    end

end

app/models/item.rb
class Item < ApplicationRecord
    
  has_many :selections 
  has_many :carts, through: :selections
  has_many :orders, through: :selections
  has_one_attached :image_url

  
  validates :title,
    presence: true, 
    length: { in: 5..140}
  
  validates :description,
    presence: true, 
    length: { in: 20..1000 }
  
  validates :price,
    presence: true,
    numericality: {greater_than: 0.00}

end

app/models/order.rb
class Order < ApplicationRecord


    belongs_to :user
    has_many :selections
    has_many :items, through: :selections 

    def total_order
        @total_order = 0

        self.selections.each do |selection|
            @total_order = selection.item.price + @total_order
        end
        return @total_order
    end

end

app/models/selection.rb
class Selection < ApplicationRecord

  belongs_to :cart 
  belongs_to :item  
  belongs_to :order, optional: true 
  
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  after_create :user_cart
  after_create :welcome_send

  has_one :cart
  has_many :orders 

  def user_cart
    Cart.create(user_id: self.id)
    puts "Voici le panier numéro #{Cart.last.id}"
  end


  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @cart = Cart.new
  end

  def create
    if user_signed_in?
      @cart = Cart.create(user: current_user)
      puts "Nouveau panier créé"
    end
  end

  def show
    @items = Item.all
    @cart = Cart.find_by(user_id: current_user.id)
    
  end

  def index
    @items = Item.all
    @cart = Cart.find_by(user_id: current_user.id)
  end


end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

	def create
    @total = params[:total].to_d
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          name: 'Rails Stripe Checkout',
          amount: (@total*100).to_i,
          currency: 'eur',
          quantity: 1
        },
      ],
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    respond_to do |format|
      format.js # renders create.js.erb
    end
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)

    @cart = Cart.find_by(user_id: current_user.id)
    @order = Order.new
    
    @order.user_id = @cart.user_id
    @order.save

    @cart.selections.each do |selection|
      selection.cart_id = nil
      selection.order_id = @order.id
      selection.save
    end

    OrderMailer.order_email(@order).deliver_now
    AdminMailer.admin_email(@order).deliver_now

  end

  def cancel
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def new 
    @item = Item.new
  end

  def index
    @items = Item.all 
    a = @items.sort_by(&:price)
    @stars = a.last(3)
    
  end

  def show
    @items = Item.find(params[:id])

    @rand_items = []
    3.times do
    rand_item = Item.find(Item.all.sample.id)
    @rand_items << rand_item 
    end
  end

  def create
    @item = Item.create(item_params) 
  end

  private 

  def item_params
    params.permit(:title, :description, :price, :image_url)
  end
  
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController

  def show
    
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = current_user.orders
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @item.picture.attach(params[:picture])
    redirect_to(item_path(@item))
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @users = User.find(params[:id])
    @orders = current_user.orders
  end

  def index
    @users = User.find(current_user.id)
    @orders = current_user.orders
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>TheCatAlogue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    
    <%= javascript_include_tag 'application' %>
    <script src="https://js.stripe.com/v3/"></script>  
  </head>

  <body class="min-vh-100 d-flex flex-column justify-content-between">
    <section class="container">
        <div class="row">
            <div class="col-lg-8">
              
              <div class=" ">

                <div class="card shadow-lg p-4 border-0">
                    <div class="card-body text-center">
                      <h4 class="text-primary">Mon Panier</h4>
                    </div>
                    <% if @cart.selections.length != 0 %>
                      <ul class="list-group list-group-flush"> 
                        <% @cart.selections.each do |selection|%>                
                          <li class="list-group-item" >
                              <div class="d-flex align-items-center justify-content-between">
                                  <a href="#!" class="text-decoration-none">
                                      <div class="d-lg-flex align-items-center">
                                          <div>
                                              <%= image_tag selection.item.image_url, alt: 'photo de chat', class: 'rounded img-4by3-lg m-4', style: 'height:100px' %>
                                              
                                          </div>
                                          <div class="ml-lg-3 mt-2">
                                              <h4 class="mb-O text-secondary"><%= selection.item.title %></h4>
                                              <p class="mb-0 text-muted"><%=selection.item.description%></p>
                                              <%= link_to "Accéder à la photo", item_path(selection.item.id), class:"btn btn-warning" %>
                                              <div class="fs-lg text-accent pt-2"><%= selection.item.price %> €</div>
                                          </div>
                                      </div>
                                  </a>
                                    <div class="pt-2 pt-sm-0 ps-sm-3 mx-auto mx-sm-0 text-center text-sm-start"     style="max-width: 9rem;">
                                    <%= link_to "Supprimer", [selection.item, selection], method: "delete", class:"btn btn-link px-0 text-danger" %>
                                    </div>
                              </div>
                          </li>
                          
                        <% end %>
                      </ul>
                    <% else %>
                      <div class="flex center">
                        <p class="text-center">Votre panier est vide pour le moment.</p>
                        <img src="https://media.giphy.com/media/TjS7u7yoMC2KubI5wE/giphy.gif" class="rounded mx-auto d-block" alt="this slowpoke moves"  width="250" /></div>
                    <% end %>
                          
                      

                </div>    
              </div>
            </div>
            <div class="col-lg-4 align-self-center">
              <div class="bg-white rounded-3 shadow-lg p-4">
                  <div class="py-2 px-xl-2">
                    <div class="text-center mb-4 pb-3 border-bottom">
                      <h2 class="h6 mb-3 pb-1">Total</h2>
                      <h3 class="fw-normal"><%= @cart.total_cart %> €</h3>
                    </div>

                    <div class="accordion" id="order-options">
                      </div><%= button_to "Procéder au paiement", checkout_create_path(total: @cart.total_cart, :id => @cart.id), class: "btn btn-primary btn-shadow d-block w-100 mt-4", remote: true %>
                      </div>
                  </div>  
            </div>
        </div>
    </section>
  </body>
</html>

app/views/carts/show.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>TheCatAlogue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    
    <%= javascript_include_tag 'application' %>
    <script src="https://js.stripe.com/v3/"></script>  
  </head>

  <body class="min-vh-100 d-flex flex-column justify-content-between">
    <section class="container">
        <div class="row">
            <div class="col-lg-8">
              
              <div class=" ">

                <div class="card shadow-lg p-4 border-0">
                    <div class="card-body text-center">
                      <h4 class="text-primary">Mon Panier</h4>
                    </div>
                    <% if @cart.selections.length != 0 %>
                      <ul class="list-group list-group-flush"> 
                        <% @cart.selections.each do |selection|%>                
                          <li class="list-group-item" >
                              <div class="d-flex align-items-center justify-content-between">
                                  <a href="#!" class="text-decoration-none">
                                      <div class="d-lg-flex align-items-center">
                                          <div>
                                              <%= image_tag selection.item.image_url, alt: 'photo de chat', class: 'rounded img-4by3-lg m-4', style: 'height:100px' %>
                                              
                                          </div>
                                          <div class="ml-lg-3 mt-2">
                                              <h4 class="mb-O text-secondary"><%= selection.item.title %></h4>
                                              <p class="mb-0 text-muted"><%=selection.item.description%></p>
                                              <%= link_to "Accéder à la photo", item_path(selection.item.id), class:"btn btn-warning" %>
                                              <div class="fs-lg text-accent pt-2"><%= selection.item.price %> €</div>
                                          </div>
                                      </div>
                                  </a>
                                    <div class="pt-2 pt-sm-0 ps-sm-3 mx-auto mx-sm-0 text-center text-sm-start"     style="max-width: 9rem;">
                                    <%= link_to "Supprimer", [selection.item, selection], method: "delete", class:"btn btn-link px-0 text-danger" %>
                                    </div>
                              </div>
                          </li>
                          
                        <% end %>
                      </ul>
                    <% else %>
                      <div class="flex center">
                        <p class="text-center">Votre panier est vide pour le moment.</p>
                        <img src="https://media.giphy.com/media/TjS7u7yoMC2KubI5wE/giphy.gif" class="rounded mx-auto d-block" alt="this slowpoke moves"  width="250" /></div>
                    <% end %>
                          
                      

                </div>    
              </div>
            </div>
            <div class="col-lg-4 align-self-center">
              <div class="bg-white rounded-3 shadow-lg p-4">
                  <div class="py-2 px-xl-2">
                    <div class="text-center mb-4 pb-3 border-bottom">
                      <h2 class="h6 mb-3 pb-1">Total</h2>
                      <h3 class="fw-normal"><%= @cart.total_cart %> €</h3>
                    </div>

                    <div class="accordion" id="order-options">
                      </div><%= button_to "Procéder au paiement", checkout_create_path(total: @cart.total_cart, :id => @cart.id), class: "btn btn-primary btn-shadow d-block w-100 mt-4", remote: true %>
                      </div>
                  </div>  
            </div>
        </div>
    </section>
  </body>
</html>

app/views/items/_items_cards.html.erb
<div class="container pt-5 pb-4 fw-bold">
    <h3 class="fw-bold display-5"> Les photos actuellement en vente </h3>
  </div>


    <section class="container card-group pb-5">
    
      <% @items.each do |item| %> 
      
        <div class="row row-cols-1 row-cols-md-2 g-4">
          <div class="col">

            <div class="card m-3 bg-white text-dark" style="width: 18rem;">
              
              <%= image_tag item.image_url, alt: 'photo de chat', class: 'card-img-top' %>          
                
              <div class="card-body text-center">
                
                <p class="card-text ">Son nom: <%= item.title%></p>
                <p class="card-text ">Sa description: <%= item.description%></p>
                <br/>
                <%= link_to "Accéder à la page de la photo", item_path(item.id), class:"btn btn-warning" %>
              <% if user_signed_in? %>
                <%= link_to "Ajouter au panier", item_selections_path(item), class:"btn btn-info", method:"POST", remote: true %>
              <% else %>
                <%= link_to "Se connecter pour l'acheter", new_user_session_path %>
              <% end %>
                
                             
              </div>
            </div>
          </div>
        </div>
        
      <% end %>
    </section>

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
<%= render 'layouts/jumbotron' %>
<%= render 'items_cards' %>

</body>
</html>

app/views/items/item.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
<div class="container pt-5 pb-4 fw-bold">
    <h3 class="fw-bold display-5"> Les photos actuellement en vente </h3>
  </div>


    <section class="container card-group pb-5">
    
      <% @items.each do |item| %> 
      
        <div class="row row-cols-1 row-cols-md-2 g-4">
          <div class="col">

            <div class="card m-3 bg-white text-dark" style="width: 18rem;">
              <p class="card-title text-muted text-center pt-3 small">Photo numéro <%= item.id%></p>
              
              <%= image_tag(item.picture)%>
              
              <!-- <img src="https://images-ext-1.discordapp.net/external/2dkSeg_r2Aj4f58DnU-LOfOLyIZfyMoTm9gYYNf_EUU/https/www.pkfoot.com/wp-content/uploads/2020/03/foot-anglais.jpg?width=1130&height=660" class="card-img-top" alt="..."> -->
              
                
              <div class="card-body text-center">
                
                <p class="card-text ">Son titre: <%= item.title%></p>
                <p class="card-text ">Sa description: <%= item.description%></p>
                <br/>
                <%= link_to "Accéder à la page de la photo", item_path(item.id), class:"btn btn-warning" %>
                             
              </div>
            </div>
          </div>
        </div>
        
      <% end %>
    </section>

</body>
</html>

app/views/items/show.html.erb
  <div class="row single-product mt-5">
    <div class="col-md-6 offset-md-2">
      <div class="row">
            <div class="col-md-5 margin-b-30">
                <div class="item">
                      <%= image_tag @items.image_url, alt: 'photo de chat', class: 'w-100' %>
                </div>
            </div>
            <div class="col-md-7">
                <div class="mx-5">
                    <h3 class="title pt-2"> <%= @items.title %></h3>
                    <span class="price"> <%= @items.price %> €</span>
                    <p class="mt-2"><%= @items.description %></p>
                    <div class="available mt-5">En stock</div>
                    <div class="add-buttons">
                        <%= link_to "Ajouter au panier", item_selections_path(@items), class:"btn btn-info", method:"POST" %>
                    </div>
                </div>
            </div>
      </div>
    </div>
 

<section class="container p-3">
<hr>
  <div class="container">
  <h2 class="text-center py-3">Produits similaires</h2>
    <div class="row justify-content-center">
      <div class="card-group">
      <% @rand_items.each do |rand_item|%>
        <div class="col mx-5">
          <div class="card" style="18rem;">
            <%= image_tag rand_item.image_url, alt: 'photo de chat', class: 'card-img-top' %>
            <div class="card-body">
              <h4 class="card-title"><%= rand_item.title %></h4>
              <p class="card-text"><%= rand_item.description %></p>
              <%= link_to "Accéder à la page de la photo", item_path(rand_item.id), class:"btn btn-warning" %>
            </div>
          </div>
        </div>
        
        <% end %>
        

        
      </div>
    </div>
  </div>
</section>    

app/views/order/index.html.erb
<div class="container pt-5 pb-4 fw-bold">
    <h3 class="fw-bold display-5"> Tes dernières commandes </h3>
  </div>


    <section class="container card-group pb-5">
    
      <% @orders.each do |item| %> 
      
        <div class="row row-cols-1 row-cols-md-2 g-4">
          <div class="col">

            <div class="card m-3 bg-white text-dark" style="width: 18rem;">
              
              <%= image_tag item.image_url, alt: 'photo de chat', class: 'card-img-top' %>
                          
                
              <div class="card-body text-center">
                
                <p class="card-text ">Son nom: <%= item.title%></p>
                <p class="card-text ">Sa description: <%= item.description%></p>
                <br/>
                <%= link_to "Accéder à la page de la photo", item_path(item.id), class:"btn btn-warning" %>
              <% if user_signed_in? %>
                <%= link_to "Ajouter au panier", item_selections_path(item), class:"btn btn-info", method:"POST" %>
              <% else %>
                <%= link_to "Se connecter pour l'acheter", new_user_session_path %>
              <% end %>
                
                             
              </div>
            </div>
          </div>
        </div>
        
      <% end %>
    </section>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Profil</title>
</head>
<body>

  <div class="container col-12 pt-5">
    <div class="row">
      <div class="col-lg-3 col-md-4 col-12">
        <div class="card border-0 mb-4">
          <div class="card-body">
            <h3>Profil</h3>
            <p> <%= @users.email %> </p>
            <%= link_to "Mettre à jour son profil", edit_user_registration_path, class:"btn btn-info" %>
          </div>
        </div>
        <div class="card border-0 mb-4">
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-between border-bottom pb-3 mb-3">
              <div>
                <h5 class="mb-0 fw-bold"><%= @orders.count %></h5>
                <p class="mb-0">Commandes passées</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-9 col-md-8 col-12">
        <div class="card p-3 border-0">
          <div class="card-body">
            <h4>Historique des commandes</h4>
          </div>
            <% @orders.each do |order| %> 
      
            <div class="row row-cols-1 row-cols-md-2 g-4">
              <div class="col">

                <div class="card m-3 bg-white text-dark" style="width: 18rem;">
                    <div class="card-header">
                      Commande n°<%= order.id%> // <%= order.created_at.strftime("%Y-%d-%m") %>
                    </div>
                  <div class="card-body text-center">
                    
                                    
                    <% order.selections.each do |selection| %>
                    <p>1 photo de <%= selection.item.title %> - <%= selection.item.price %> €
                    
                    <%= link_to "Accéder à la page de la photo", item_path(selection.item.id), class:"btn btn-warning btn-sm" %></p>
                    
                    <% end %>
                    
                                
                  </div>
                  <div class="card-footer">
                    Prix total : <%= order.total_order %> €
                  </div>
                </div>
              </div>
            </div>
            
          <% end %>
        </div>
      </div>
    </div>
  </div>
  
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Profil</title>
</head>
<body>

  <div class="container col-12 pt-5">
    <div class="row">
      <div class="col-lg-3 col-md-4 col-12">
        <div class="card border-0 mb-4">
          <div class="card-body">
            <h3>Profil</h3>
            <p> <%= @users.email %> </p>
          </div>
        </div>
        <div class="card border-0 mb-4">
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-between border-bottom pb-3 mb-3">
              <div>
                <h5 class="mb-0 fw-bold"><%= @orders.count %></h5>
                <p class="mb-0">Commandes passées</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-9 col-md-8 col-12">
        <div class="card p-3 border-0">
          <div class="card-body">
            <h4>Historique des commandes</h4>
          </div>
            <% @orders.each do |order| %> 
      
            <div class="row row-cols-1 row-cols-md-2 g-4">
              <div class="col">

                <div class="card m-3 bg-white text-dark" style="width: 18rem;">
                    <div class="card-header">
                      Commande n°<%= order.id%>
                    </div>
                  <div class="card-body text-center">
                    
                                    
                    <% order.selections.each do |selection| %>
                    <p>1 photo de <%= selection.item.title %> - <%= selection.item.price %> €
                    
                    <%= link_to "Accéder à la page de la photo", item_path(selection.item.id), class:"btn btn-warning btn-sm" %></p>
                    
                    <% end %>
                    
                                
                  </div>
                  <div class="card-footer">
                    Prix total : <%= order.total_order %> €
                  </div>
                </div>
              </div>
            </div>
            
          <% end %>
        </div>
      </div>
    </div>
  </div>
  
</body>
</html>