config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  root "items#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items, path: "photos" do
    resources :selections
    resources :pictures, only: [:create]
  end

  resources :layouts, only: [:index], path: "notre_equipe" 
  resources :carts, only: [:new, :create, :index], path: "mon_panier"
  resources :orders, path: "vos_commandes"
  resources :users, path: "mon_profil"

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :trackable, :timeoutable, :lockable 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :selections
    has_many :items, through: :selections


    def total_cart
        @total_cart = 0

        self.selections.each do |selection|
            @total_cart = selection.item.price + @total_cart
        end
        return @total_cart
    end

end

app/models/item.rb
class Item < ApplicationRecord
    
  has_many :selections 
  has_many :carts, through: :selections
  has_many :orders, through: :selections
  has_one_attached :image_url

  
  validates :title,
    presence: true, 
    length: { in: 5..140}
  
  validates :description,
    presence: true, 
    length: { in: 20..1000 }
  
  validates :price,
    presence: true,
    numericality: {greater_than: 0.00}

end

app/models/order.rb
class Order < ApplicationRecord


    belongs_to :user
    has_many :selections
    has_many :items, through: :selections 

    def total_order
        @total_order = 0

        self.selections.each do |selection|
            @total_order = selection.item.price + @total_order
        end
        return @total_order
    end

end

app/models/selection.rb
class Selection < ApplicationRecord

  belongs_to :cart 
  belongs_to :item  
  belongs_to :order, optional: true 
  
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  after_create :user_cart
  after_create :welcome_send

  has_one :cart
  has_many :orders 

  def user_cart
    Cart.create(user_id: self.id)
    puts "Voici le panier numéro #{Cart.last.id}"
  end


  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @cart = Cart.new
  end

  def create
    if user_signed_in?
      @cart = Cart.create(user: current_user)
      puts "Nouveau panier créé"
    end
  end

  def show
    @items = Item.all
    @cart = Cart.find_by(user_id: current_user.id)
    
  end

  def index
    @items = Item.all
    @cart = Cart.find_by(user_id: current_user.id)
  end


end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

	def create
    @total = params[:total].to_d
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          name: 'Rails Stripe Checkout',
          amount: (@total*100).to_i,
          currency: 'eur',
          quantity: 1
        },
      ],
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    respond_to do |format|
      format.js # renders create.js.erb
    end
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)

    @cart = Cart.find_by(user_id: current_user.id)
    @order = Order.new
    
    @order.user_id = @cart.user_id
    @order.save

    @cart.selections.each do |selection|
      selection.cart_id = nil
      selection.order_id = @order.id
      selection.save
    end

    OrderMailer.order_email(@order).deliver_now
    AdminMailer.admin_email(@order).deliver_now

  end

  def cancel
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def new 
    @item = Item.new
  end

  def index
    @items = Item.all 
    a = @items.sort_by(&:price)
    @stars = a.last(3)
    
  end

  def show
    @items = Item.find(params[:id])

    @rand_items = []
    3.times do
    rand_item = Item.find(Item.all.sample.id)
    @rand_items << rand_item 
    end
  end

  def create
    @item = Item.create(item_params) 
  end

  private 

  def item_params
    params.permit(:title, :description, :price, :image_url)
  end
  
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController

  def show
    
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = current_user.orders
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @users = User.find(params[:id])
    @orders = current_user.orders
  end

  def index
    @users = User.find(current_user.id)
    @orders = current_user.orders
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checkout/cancel.html.erb
<div class="container text-center my-5">
	<h1>Echec</h1>
  <p>Le paiement n'a pas abouti.</p>
</div>

app/views/checkout/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');
stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then(function (result) {
  console.log(result.error.message);
});

app/views/checkout/success.html.erb
<div class="container text-center my-5">
  <h1>Succès</h1>
  <p>Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.</p>
  <p>Le statut de votre paiement est : <%= @payment_intent.status %>.</p>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg|%>
  <div class="alert alert-<%= name %>"><%= msg %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="flex text-center text-white bg-secondary d-flex flex-column justify-content-end">

  <!-- Copyright -->
  <div class="text-center p-2 bg-secondary ">
    
  <p class="m-1">© 2021 Copyright: The Cat-Alogue x Les Francs-Développeur.e.s <br>
  <a href="#top" class="font-decoration-none text-light">Back to the top <i class="fas fa-arrow-up"></i></a></p>
  </div>
  <!-- Copyright -->
</footer>

<!-- Optional JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- Optional JavaScript -->

app/views/layouts/_jumbotron.html.erb
<section class="jumbotron py-5 py-lg-10 text-center bg-light d-flex flex-column justify-content-center" >
  <div class="container pb-5">
    <div class="row justify-content-center col-md-12 pb-5">
      <div class="col-xl-6 col-lg-7 col-md-8 col-sm-10 text-center pt-5">
      <h5 class="text-light fw-light pt-5">Bienvenue sur le Cat-Alogue by THP </h5>
        <div class="pb-4"> 
          <h1 class="text-light font-weight-bold pt-3 fw-bold">Parcourez et achetez les photos des plus beaux chats de France</h1>  
        <% if user_signed_in? == false %>
          <%= link_to 'Se connecter', new_user_session_path, class: "btn btn-primary" %>
        <% end %>
        </div>      
      </div>
    </div>
  </div>
</section>

<div class="container">
  <h1>Les Stars du Cat-Alogue</h1>
  <div class="row">
    <% @stars.each do |item| %>
      <div class="col-md-4">
        <h2><%= item.title %></h2>
        <%= image_tag item.image_url, alt: "Photo de star", class: 'card-img-top' %>
        <p> <%= item.description %> </p>
        <p> <%= item.price %>€</p>
        <%= link_to "Accéder à la photo", item_path(item.id), class:"btn btn-warning" %>  
        <%= link_to "Ajouter au panier", item_selections_path(item), class:"btn btn-info", method:"POST", remote:true %>  
      </div>
      
    <% end %>
    
  </div>

  <hr>

</div>

app/views/layouts/_navbar.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container-fluid">
    <ul class="navbar-nav justify-content-start">
      <a class="navbar-brand text-white" href="/">
      <i class="fas fa-cat"></i>
      Cat-Alogue
      </a>

        <li class="nav-item">
          <a class="nav-link active text-white" href="/">Accueil
          </a>
        </li>
        <li class="nav-item">
          <%= link_to "L'équipe", layouts_path, class: "nav-link active text-white" %>

          </a>
        </li>
      </ul>
<%if user_signed_in? %>
      <ul class="navbar-nav justify-content-end">
        <li class="nav-item dropdown active ">
          <a class="nav-link dropdown-toggle active text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Mon espace 
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", users_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item bg-danger text-white", method: :delete %>
          </div>
        </li>
        <li>
          <%= link_to carts_path, class: 'btn btn-primary' do %>
            <span class="glyphicon glyphicon-eye-open"></span> <i class="fas fa-shopping-cart" id="cart-btn-value"> <%=Cart.find_by(user_id: current_user.id).selections.length %></i>
          <% end %>
        </li>
        </ul>
<% else %>
      <ul class="navbar-nav">
        <li class="nav-item dropdown active ">
          <a class="nav-link dropdown-toggle active text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Se connecter                   
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Se connecter', new_user_session_path, class: "dropdown-item " %>
            <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %>
          </div>
        </li>
<% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>TheCatAlogue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    
    <%= javascript_include_tag 'application' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= render 'layouts/navbar' %>
    <%= render "layouts/flash" %>
  </head>

  <body class="min-vh-100 d-flex flex-column justify-content-between">
    
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/index.html.erb
<body class="min-vh-100 d-flex flex-column justify-content-between">
  <div class="container-fluid">

      <div class="card p-2">
        <div class="card-body text-center">
          <h2 class="text-primary">L'équipe Cat-Alogue</h2>

<div class="d-md-flex flex-md-equal">
    <div class="bg-light col-6 me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Paul Durant</h2>
        <p class="lead">Photographe depuis une vingtaine d’années</p>
        
      </div>
      <div class="team_1 bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-light col-6 me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Lucie Martin</h2>
        <p class="lead">Commerciale et passionnée de nos amis félins</p>
      </div>
      <div class="team_2 bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>

        </div>
      </div>        

  </div>

</body>